### ISSUE TITLE
UNREAD-CHAR is missing an Exceptional Situations section

### ISSUE THREAD

**Issue by yitzchak** [s-expressionists/wscl#36]
The entry for UNREAD-CHAR in the spec does not have an "Exceptional Situations" section but has several statements which seem to suggest that errors will be signaled.

1. The "Arguments and Values" section states "character — a character; must be the last character that was read from input-stream."  It does not say what should be done if the character does not match the previous character that was read.
2. The "Description" sections states "It is an error to invoke unread-char twice consecutively on the same stream without an intervening call to read-char ... " but does not specify what kind of error should be signaled.

**Comment by Bike** [comment]
1.4.2 Error Terminology specifies that if "it is an error" but no type is specified, it's `cl:error`. Not that this means mentioning it in Exceptional Situations and/or specifying a more specific error might not be bad.

**Comment by yitzchak** [comment]
A discussion on [irc](https://irclog.tymoon.eu/libera/%23commonlisp?around=1702360882#1702360882)  today also points to the glossary entry n. 1: 

> error n. 1. (only in the phrase ``is an error'') a situation in which the semantics of a program are not specified, and in which the consequences are undefined. 2. a condition which represents an error situation. See Section 1.4.2 (Error Terminology). 3. an object of type error.

**Comment by robert-strandh** [comment]
Closed as a result of issue report unread-char-exceptional-situations
