### ISSUE TITLE
Dictionary entry for MAPC and related functions mentions a result-type

### ISSUE THREAD

**Issue by scymtym** [s-expressionists/wscl#37]
The dictionary entry for `mapc` and related functions contains the sentence

> result-type specifies the type of the resulting sequence.

which does not make sense in the context at hand. The sentence was probably accidentally copied from the dictionary entry for `map`.

**Comment by robert-strandh** [comment]
Closed as a result of issue MAPC-ETC-REMOVE-RESULT-TYPE
