### ISSUE TITLE
RESTART-CASE syntax error

### ISSUE THREAD

**Issue by robert-strandh** [s-expressionists/wscl#55]
The dictionary entry for RESTART-CASE says the syntax is
restart-case restartable-form {clause} -> {result}* but it should be
restart-case restartable-form {clause}* -> {result}*

**Comment by scymtym** [comment]
I believe this is a duplicate of #30.

**Comment by robert-strandh** [comment]
You are right of course.  For some reason #30 didn't show up at first. 
And I am not sure what I did in order for it to show up.
